# fly.toml app configuration file generated for rescutex-db on 2026-04-21T12:31:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rescutex-db'
primary_region = 'gru'
kill_signal = 'SIGTERM'

[build]
  dockerfile = 'Dockerfile'

[env]
  PGDATA = '/data/postgres'
  POSTGRES_DB = 'rescute_db_prod'
  POSTGRES_USER = 'rescute'

[processes]
  app = "sh -c 'mkdir -p /data/postgres && chown postgres:postgres /data/postgres && exec docker-entrypoint.sh postgres'"

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
